/**
 * Termii SMS service for transactional messages (delivery confirmations, parcel alerts).
 * NOTE: Supabase Auth handles auth OTPs via its own SMS provider.
 * Termii is used for operational SMS only (e.g. delivery OTP, parcel alerts).
 */
import axios from 'axios'

const TERMII_BASE = 'https://api.ng.termii.com/api'

/**
 * Send a plain transactional SMS via Termii.
 */
export async function sendSMS(to: string, message: string): Promise<boolean> {
  const apiKey = process.env.TERMII_API_KEY
  if (!apiKey) {
    console.warn('[Termii] TERMII_API_KEY not set — SMS disabled')
    return false
  }

  try {
    await axios.post(`${TERMII_BASE}/sms/send`, {
      api_key: apiKey,
      to,
      from: process.env.TERMII_SENDER_ID ?? 'CarryMate',
      sms: message,
      type: 'plain',
      channel: 'generic',
    })
    return true
  } catch (err) {
    console.error('[Termii] SMS send failed:', err)
    return false
  }
}

/**
 * Send a delivery OTP SMS to a recipient.
 * The OTP itself is generated by the bookings router and stored in the DB.
 */
export async function sendDeliveryOtpSMS(recipientPhone: string, otp: string): Promise<boolean> {
  const message = `Your CarryMate delivery code is ${otp}. Share this ONLY with your traveler when they hand over your parcel. Valid for 24 hours.`
  return sendSMS(recipientPhone, message)
}

/**
 * Send a parcel matched alert SMS to a sender.
 */
export async function sendParcelMatchedSMS(senderPhone: string, travelerName: string): Promise<boolean> {
  const message = `Great news! A traveler (${travelerName}) has accepted your CarryMate parcel. Open the app for details.`
  return sendSMS(senderPhone, message)
}
